version: '3.7'

services:
  scorecard:
    image: python:3.8-slim
    restart: always
    container_name: scorecard
    entrypoint: [./entrypoint.sh, development]
    env_file: ./env/dev.env
    ports:
      - '5001:5000'
    working_dir: /app
    volumes:
      - ./:/app

  scorecard-test:
    image: python:3.8-slim
    restart: always
    container_name: scorecard-test
    entrypoint: [./entrypoint.sh, development]
    env_file: ./env/test.env
    working_dir: /app
    volumes:
      - ./:/app

  scorecard-db:
    image: postgres:12-alpine
    restart: always
    container_name: scorecard-db
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
