version: '3.7'

services:
  scorecard:
    build:
      context: .
      target: development
    restart: always
    container_name: scorecard
    env_file: ./env/dev.env
    ports:
      - '5001:5000'
      - '5678:5678'
    volumes:
      - ./:/app
      - ~/dev/uploads/scorecard/player-photos:/uploads/player-photos

  scorecard-test:
    build:
      context: .
      target: test
    container_name: scorecard-test
    env_file: ./env/test.env
    volumes:
      - ./:/app

  scorecard-redis:
    image: redis:7-alpine
    restart: always
    container_name: scorecard-redis
    env_file: ./env/redis.env
    volumes:
      - redis_data:/data
      - ./redis:/usr/local/etc/redis

  scorecard-db:
    image: postgres:12-alpine
    restart: always
    container_name: scorecard-db
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
