version: '3.7'

services:
  scorecard:
    build:
      context: .
      target: development
    restart: always
    container_name: scorecard
    env_file: ./env/dev.env
    ports:
      - '5001:5000'
      - '5678:5678'
    volumes:
      - ./:/app

  scorecard-test:
    build:
      context: .
      target: test
    container_name: scorecard-test
    env_file: ./env/test.env
    volumes:
      - ./:/app

  scorecard-db:
    image: postgres:12-alpine
    restart: always
    container_name: scorecard-db
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
