"""Add a tournaments table

Revision ID: 596913905ae8
Revises: 9277f4066f94
Create Date: 2020-11-09 02:26:47.500160

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "596913905ae8"
down_revision = "9277f4066f94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournaments")
    # ### end Alembic commands ###
