"""Add column for player photo

Revision ID: 70c93e47ec60
Revises: 9810f820654e
Create Date: 2021-05-12 17:04:13.810573

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70c93e47ec60"
down_revision = "9810f820654e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("photo_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "photo_path")
    # ### end Alembic commands ###
