"""Add not null constraint

Revision ID: 73a0557bbf16
Revises: e35c9e3e32a9
Create Date: 2020-11-12 06:55:15.819731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a0557bbf16'
down_revision = 'e35c9e3e32a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_name', 'match_formats', ['name'])
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_name', 'match_formats', type_='unique')
    # ### end Alembic commands ###
