"""Add tee set table.

Revision ID: 8ea955889317
Revises: 3a44137454d8
Create Date: 2020-11-10 03:43:06.425006

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ea955889317"
down_revision = "3a44137454d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tee_sets",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("tee_color_id", sa.Integer(), nullable=False),
        sa.Column("slope", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.CheckConstraint("slope >= 55 AND slope <= 155"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tee_color_id"], ["tee_colors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("course_id", "tee_color_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tee_sets")
    # ### end Alembic commands ###
