"""Add players table

Revision ID: 9277f4066f94
Revises:
Create Date: 2020-11-05 13:04:28.752577

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9277f4066f94"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=32), nullable=False),
        sa.Column("hdcp", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk__players"),
        sa.UniqueConstraint("email", name="uq__players__email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
