"""Add handicapped column

Revision ID: 9810f820654e
Revises: be545f06fbd5
Create Date: 2021-05-06 20:01:47.728978

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9810f820654e"
down_revision = "be545f06fbd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("handicapped", sa.Boolean(), nullable=True))
    op.execute("UPDATE matches SET handicapped = false")
    op.alter_column("matches", "handicapped", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "handicapped")
    # ### end Alembic commands ###
