"""Added new columns to Player

Revision ID: 9da1412da150
Revises: 2e6b4636e695
Create Date: 2025-08-01 16:26:05.693548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da1412da150'
down_revision = '2e6b4636e695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('cups', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('losses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('ties', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('wins', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'wins')
    op.drop_column('players', 'ties')
    op.drop_column('players', 'losses')
    op.drop_column('players', 'cups')
    # ### end Alembic commands ###
