"""Add biography column

Revision ID: a9ab94977cf5
Revises: 70c93e47ec60
Create Date: 2021-05-13 00:40:45.100688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9ab94977cf5"
down_revision = "70c93e47ec60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("biography", sa.Text(), nullable=True))
    op.execute("UPDATE players SET biography = '', photo_path = ''")
    op.alter_column("players", "biography", nullable=False)
    op.alter_column("players", "photo_path", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "photo_path", nullable=True)
    op.drop_column("players", "biography")
    # ### end Alembic commands ###
