"""Add courses table

Revision ID: aba0d41f33eb
Revises: a627ad645c25
Create Date: 2020-11-09 21:10:47.513343

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aba0d41f33eb"
down_revision = "a627ad645c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk__courses"),
        sa.UniqueConstraint("name", name="uq__courses__name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses")
    # ### end Alembic commands ###
