"""Add holes table.

Revision ID: aec707e77fce
Revises: 8ea955889317
Create Date: 2020-11-10 07:29:48.003205

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aec707e77fce"
down_revision = "8ea955889317"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holes",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("tee_color_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("par", sa.Integer(), nullable=False),
        sa.Column("hdcp", sa.Integer(), nullable=False),
        sa.Column("yards", sa.Integer(), nullable=False),
        sa.CheckConstraint("hdcp >= 1 AND hdcp <= 18"),
        sa.CheckConstraint("number >= 1 AND number <= 18"),
        sa.CheckConstraint("par >= 3 AND par <= 6"),
        sa.ForeignKeyConstraint(
            ["course_id", "tee_color_id"], ["tee_sets.course_id", "tee_sets.tee_color_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tee_color_id"],
            ["tee_colors.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "tee_color_id", "number"),
        sa.UniqueConstraint("course_id", "tee_color_id", "hdcp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("holes")
    # ### end Alembic commands ###
