"""Add a unique constraint.

Revision ID: b2343116bed2
Revises: 015aaa0f37fd
Create Date: 2020-11-10 19:33:04.752036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2343116bed2'
down_revision = '015aaa0f37fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_id_course_id_tee_color_id', 'matches', ['id', 'course_id', 'tee_color_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_id_course_id_tee_color_id', 'matches', type_='unique')
    # ### end Alembic commands ###
