"""Add match formats table.

Revision ID: bd85d5151d12
Revises: aec707e77fce
Create Date: 2020-11-10 08:36:19.235569

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bd85d5151d12"
down_revision = "aec707e77fce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_formats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk__match_formats"),
        sa.UniqueConstraint("name", name="uq__match_formats_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_formats")
    # ### end Alembic commands ###
