"""Remove delete cascade

Revision ID: be545f06fbd5
Revises: 692fa71e45e4
Create Date: 2020-11-24 19:36:45.174924

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "be545f06fbd5"
down_revision = "692fa71e45e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("matches_course_id_tee_color_id_fkey", "matches", type_="foreignkey")
    op.create_foreign_key(None, "matches", "tee_sets", ["course_id", "tee_color_id"], ["course_id", "tee_color_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.create_foreign_key(
        "matches_course_id_tee_color_id_fkey",
        "matches",
        "tee_sets",
        ["course_id", "tee_color_id"],
        ["course_id", "tee_color_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
