"""Add scores table.

Revision ID: e35c9e3e32a9
Revises: b2343116bed2
Create Date: 2020-11-10 19:34:21.630924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35c9e3e32a9'
down_revision = 'b2343116bed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('tee_color_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.CheckConstraint('strokes > 0'),
    sa.ForeignKeyConstraint(['course_id', 'tee_color_id', 'hole_number'], ['holes.course_id', 'holes.tee_color_id', 'holes.number'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['match_id', 'course_id', 'tee_color_id'], ['matches.id', 'matches.course_id', 'matches.tee_color_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id', 'player_id'], ['match_participants.match_id', 'match_participants.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tee_color_id'], ['tee_colors.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id', 'hole_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
